### ISSUE TITLE
[Question] Using this project

### ISSUE THREAD

**Issue by alexandesigner** [nuxt-community/electron-template#15]
Today to use this repository it is necessary to make a clone, why not add it to ``vue-cli`` so that users can only start it with ```vue init nuxt-community/electron-template <folder>```, there is some restriction so you have not done so? 

If it is the case I can send a PR with the changes

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/electron-template/issues/c11">#c11</a>)</em></sub></div>

**Comment by fredgig** [comment]
Attempting to `npm run dev` this template will cause an error (electron-userland/electron-compile#287). Apparently, using electron-webpack instead of electron-compile resolves the error according to the following issue:

Gum-Joe/tara#10

If possible, please keep this template up to date by utilizing webpacks!

**Comment by alexandesigner** [comment]
@HoraceKeung How cool, if you need any help to keep it, please let me know .. Maybe this repository can be merged with this, what do you think? @pi0

**Comment by HoraceKeung** [comment]
Thanks, I would love to contribute to this repo. As I have mentioned in https://nuxtjs.cmty.io/nuxt-community/electron-template/issues/c14, there are differences that has to be taken into consideration.

**Comment by detrohutt** [comment]
@HoraceKeung @alexandesigner I originally created this repo but "officially" stepped down as maintainer quite a while ago because I'm no longer using nuxt in my personal project (which takes up all my time). So I've been "out of the loop" for a long time and I'm not familiar with any of the changes that would be needed to update this repo, but I still have write access. If you guys can put together a pull request and test that it doesn't break any current behavior, I'll merge it.

**Comment by HoraceKeung** [comment]
@detrohutt I was trying to push a new branch but I may not have the permission.

**Comment by detrohutt** [comment]
@HoraceKeung You'll need to fork this repo, edit your fork with the necessary changes, and then open a pull request pointing to your fork.

**Comment by detrohutt** [comment]
Thanks! I'll review it later tonight and if everything looks good I'll merge it. If not, I'll let you know what needs changing.

**Comment by detrohutt** [comment]
Nuxtron has been merged with this repo. The original version is available on the `git-clone` branch.

**Comment by alexandesigner** [comment]
Awesome @detrohutt, thank you!
